services:
  db:
    image: postgres:18.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: userexample
      POSTGRES_PASSWORD: example
      POSTGRES_DB: exampledb
    ports:
      - 5432:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080